# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
      - GITHUB_TOKEN={{ .Env.GITHUB_TOKEN }}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

#
project_name: tk

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: "https://github.com/thiskevinwang/tk"
    description: "Example binary distribution using homebrew."
    folder: Formula
    commit_author:
      name: kevinwang
      email: kwangsan@gmail.com
    tap:
      owner: thiskevinwang
      name: tk

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
